import { MaterialIcons } from "@expo/vector-icons";
import { Modal, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { SafeAreaView, useSafeAreaInsets } from "react-native-safe-area-context";

import { useColors } from "@/hooks/use-colors";
import type { SurveyCycle, SurveyResult } from "@/lib/types/survey-types";

type CycleSummary = { resultCount: number; storeCount: number; averagePresencePercentage: number };

export function SurveyCycleHistoryCard({ cycle, summary, mediaCount, onPress }: { cycle: SurveyCycle; summary: CycleSummary; mediaCount: number; onPress: () => void }) {
  const colors = useColors();
  return <TouchableOpacity onPress={onPress} activeOpacity={0.82} style={[styles.historyCard, { backgroundColor: colors.surface, borderColor: colors.border }]}>
    <View style={styles.historyTop}><View style={[styles.historyIcon, { backgroundColor: colors.accent + "16" }]}><MaterialIcons name="history" size={22} color={colors.accent} /></View><View style={styles.historyText}><Text style={[styles.historyTitle, { color: colors.foreground }]} numberOfLines={1}>{cycle.name}</Text><Text style={[styles.historyDate, { color: colors.muted }]}>{cycle.startDate} — {cycle.endDate}</Text></View><MaterialIcons name="chevron-left" size={22} color={colors.muted} /></View>
    <View style={styles.metrics}><Metric color={colors.accent} icon="storefront" value={summary.storeCount} label="محلات" /><Metric color={colors.success} icon="check-circle" value={`${summary.averagePresencePercentage}%`} label="تواجد" /><Metric color={colors.primary} icon="photo-library" value={mediaCount} label="وسائط" /></View>
  </TouchableOpacity>;
}

export function SurveyCycleDetailScreen({ cycle, results, visible, isDeletingMedia, onClose, onDeleteMedia }: { cycle: SurveyCycle | null; results: SurveyResult[]; visible: boolean; isDeletingMedia: boolean; onClose: () => void; onDeleteMedia: () => void }) {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  if (!cycle) return null;
  const mediaCount = results.reduce((total, result) => total + (result.storePhotoUris?.length || (result.storePhotoUri ? 1 : 0)), 0);
  const productRows = results.flatMap((result) => result.data);
  const presentRows = productRows.filter((item) => item.present).length;
  const averagePresence = productRows.length ? Math.round((presentRows / productRows.length) * 100) : 0;
  return <Modal visible={visible} animationType="slide" presentationStyle="pageSheet" onRequestClose={onClose}><SafeAreaView edges={["top", "left", "right"]} style={[styles.page, { backgroundColor: colors.background }]}>
    <View style={[styles.pageHeader, { backgroundColor: colors.surface, borderBottomColor: colors.border }]}><TouchableOpacity onPress={onClose} accessibilityLabel="إغلاق تفاصيل الدورة"><MaterialIcons name="close" size={24} color={colors.foreground} /></TouchableOpacity><Text style={[styles.pageTitle, { color: colors.foreground }]}>تفاصيل الدورة</Text><View style={{ width: 24 }} /></View>
    <ScrollView contentContainerStyle={[styles.detailContent, { paddingBottom: insets.bottom + 98 }]}>
      <View style={[styles.hero, { backgroundColor: colors.accent }]}><View style={styles.heroIcon}><MaterialIcons name="event-available" size={25} color="#fff" /></View><Text style={styles.heroTitle}>{cycle.name}</Text><Text style={styles.heroSubtitle}>{cycle.startDate} — {cycle.endDate}</Text></View>
      <View style={styles.detailMetrics}><Metric color={colors.accent} icon="assignment" value={results.length} label="استبيانات" /><Metric color={colors.success} icon="storefront" value={new Set(results.map((result) => result.storeId)).size} label="محلات" /><Metric color={colors.primary} icon="pie-chart" value={`${averagePresence}%`} label="متوسط التواجد" /><Metric color={colors.warning} icon="photo-library" value={mediaCount} label="وسائط" /></View>
      <View style={[styles.detailSection, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.sectionTitle, { color: colors.foreground }]}>محلات الدورة</Text>{results.map((result, index) => <View key={result.id} style={[styles.resultRow, index < results.length - 1 && { borderBottomColor: colors.border, borderBottomWidth: StyleSheet.hairlineWidth }]}><View style={[styles.resultIcon, { backgroundColor: colors.accent + "14" }]}><MaterialIcons name="store" size={19} color={colors.accent} /></View><View style={styles.resultText}><Text style={[styles.resultName, { color: colors.foreground }]}>{result.storeName}</Text><Text style={[styles.resultMeta, { color: colors.muted }]}>{result.storeRegion} • {result.surveyDate}</Text></View><Text style={[styles.mediaBadge, { color: colors.primary, backgroundColor: colors.primary + "12" }]}>{result.storePhotoUris?.length || (result.storePhotoUri ? 1 : 0)} صورة</Text></View>)}</View>
      <View style={[styles.dangerSection, { backgroundColor: colors.error + "0D", borderColor: colors.error + "35" }]}><MaterialIcons name="delete-forever" size={25} color={colors.error} /><View style={styles.dangerText}><Text style={[styles.dangerTitle, { color: colors.foreground }]}>حذف وسائط الدورة</Text><Text style={[styles.dangerBody, { color: colors.muted }]}>سيُحذف نهائياً {mediaCount} ملفاً من صور المحلات، بينما تبقى النتائج والأرقام والدورة في السجل.</Text></View></View>
    </ScrollView>
    <View style={[styles.detailFooter, { backgroundColor: colors.surface, borderTopColor: colors.border, paddingBottom: insets.bottom + 8 }]}><TouchableOpacity disabled={!mediaCount || isDeletingMedia} onPress={onDeleteMedia} style={[styles.deleteMediaButton, { backgroundColor: colors.error }, (!mediaCount || isDeletingMedia) && { opacity: 0.5 }]}><MaterialIcons name="delete-forever" size={20} color="#fff" /><Text style={styles.deleteMediaText}>{isDeletingMedia ? "جارٍ الحذف النهائي..." : mediaCount ? `حذف وسائط الدورة (${mediaCount})` : "لا توجد وسائط لحذفها"}</Text></TouchableOpacity></View>
  </SafeAreaView></Modal>;
}

function Metric({ icon, value, label, color }: { icon: keyof typeof MaterialIcons.glyphMap; value: string | number; label: string; color: string }) { return <View style={styles.metric}><View style={[styles.metricIcon, { backgroundColor: color + "14" }]}><MaterialIcons name={icon} size={17} color={color} /></View><Text style={[styles.metricValue, { color }]}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }

const styles = StyleSheet.create({
  historyCard: { borderWidth: 1, borderRadius: 18, padding: 14, marginBottom: 10 }, historyTop: { flexDirection: "row", alignItems: "center", gap: 10 }, historyIcon: { width: 40, height: 40, borderRadius: 13, justifyContent: "center", alignItems: "center" }, historyText: { flex: 1, alignItems: "flex-end" }, historyTitle: { fontSize: 14, fontWeight: "900", textAlign: "right" }, historyDate: { fontSize: 11, marginTop: 3, textAlign: "right" }, metrics: { flexDirection: "row", gap: 8, marginTop: 14 }, metric: { flex: 1, alignItems: "center" }, metricIcon: { width: 30, height: 30, borderRadius: 10, justifyContent: "center", alignItems: "center" }, metricValue: { fontSize: 13, fontWeight: "900", marginTop: 4 }, metricLabel: { fontSize: 10, color: "#6B7280", marginTop: 1 }, page: { flex: 1 }, pageHeader: { minHeight: 58, borderBottomWidth: 1, paddingHorizontal: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, pageTitle: { fontSize: 17, fontWeight: "900" }, detailContent: { padding: 14 }, hero: { borderRadius: 22, padding: 18, alignItems: "flex-end" }, heroIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: "#ffffff22", justifyContent: "center", alignItems: "center", alignSelf: "flex-end" }, heroTitle: { color: "#fff", fontSize: 18, fontWeight: "900", marginTop: 10, textAlign: "right" }, heroSubtitle: { color: "#fff", opacity: 0.88, fontSize: 12, marginTop: 4 }, detailMetrics: { flexDirection: "row", flexWrap: "wrap", gap: 9, marginVertical: 14 }, detailSection: { borderWidth: 1, borderRadius: 18, padding: 14 }, sectionTitle: { fontSize: 15, fontWeight: "900", textAlign: "right", marginBottom: 8 }, resultRow: { minHeight: 60, flexDirection: "row", alignItems: "center", gap: 9, paddingVertical: 8 }, resultIcon: { width: 36, height: 36, borderRadius: 12, justifyContent: "center", alignItems: "center" }, resultText: { flex: 1, alignItems: "flex-end" }, resultName: { fontSize: 13, fontWeight: "800", textAlign: "right" }, resultMeta: { fontSize: 10, marginTop: 2, textAlign: "right" }, mediaBadge: { fontSize: 10, fontWeight: "800", borderRadius: 8, paddingHorizontal: 7, paddingVertical: 4 }, dangerSection: { borderWidth: 1, borderRadius: 18, padding: 14, marginTop: 14, flexDirection: "row", gap: 10, alignItems: "flex-start" }, dangerText: { flex: 1, alignItems: "flex-end" }, dangerTitle: { fontSize: 13, fontWeight: "900", textAlign: "right" }, dangerBody: { fontSize: 11, lineHeight: 17, textAlign: "right", marginTop: 3 }, detailFooter: { borderTopWidth: 1, padding: 12 }, deleteMediaButton: { minHeight: 51, borderRadius: 15, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 }, deleteMediaText: { color: "#fff", fontSize: 13, fontWeight: "900" },
});
