import { StyleSheet, Text, View } from "react-native";
import Svg, { Circle, G, Line, Polygon, Polyline, Rect, Text as SvgText } from "react-native-svg";

import { useColors } from "@/hooks/use-colors";
import type { ChartType } from "@/lib/analytics-settings";
import type { MarketingAnalyticsSummary } from "@/lib/marketing-analytics";

const CHART_LABELS: Record<ChartType, string> = { line: "خطي", bar: "أعمدة", pie: "دائري", area: "مساحي", scatter: "نقاط", radar: "رادار", candlestick: "شمعدان" };
const COLORS = ["#2563EB", "#0E9F6E", "#7C3AED"];

export function MarketingAnalyticsChart({ data, chartType }: { data: MarketingAnalyticsSummary; chartType: ChartType }) {
  const colors = useColors();
  const values = [{ label: "الفعاليات", value: data.events.length }, { label: "اللوحات", value: data.activeSignages }, { label: "الستاندات", value: data.activeStands }];
  const max = Math.max(1, ...values.map((item) => item.value)); const width = 320; const height = 174; const baseline = 140; const xAt = (index: number) => 54 + index * 106; const yAt = (value: number) => baseline - value / max * 100;
  const svg = chartType === "pie" ? <Pie values={values.map((item) => item.value)} colors={COLORS} /> : chartType === "radar" ? <Radar values={values.map((item) => item.value / max * 100)} colors={COLORS} /> : chartType === "bar" || chartType === "candlestick" ? <Bars values={values.map((item) => item.value)} colors={COLORS} xAt={xAt} yAt={yAt} baseline={baseline} candlestick={chartType === "candlestick"} /> : <Trend values={values.map((item) => item.value)} colors={COLORS} xAt={xAt} yAt={yAt} baseline={baseline} area={chartType === "area"} scatter={chartType === "scatter"} />;
  return <View style={[styles.card, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.title, { color: colors.foreground }]}>مؤشرات النشاط التسويقي — مخطط {CHART_LABELS[chartType]}</Text><Svg width={width} height={height} viewBox={`0 0 ${width} ${height}`}><Line x1="25" x2="305" y1={baseline} y2={baseline} stroke={colors.border} />{svg}{values.map((item, index) => <SvgText key={item.label} x={xAt(index)} y="164" textAnchor="middle" fill={colors.muted} fontSize="11">{item.label}</SvgText>)}</Svg></View>;
}

function Trend({ values, colors, xAt, yAt, baseline, area, scatter }: { values: number[]; colors: string[]; xAt: (index: number) => number; yAt: (value: number) => number; baseline: number; area: boolean; scatter: boolean }) { const points = values.map((value, index) => `${xAt(index)},${yAt(value)}`).join(" "); return <>{area ? <Polygon points={`${xAt(0)},${baseline} ${points} ${xAt(values.length - 1)},${baseline}`} fill={colors[0] + "28"} /> : null}{scatter ? null : <Polyline points={points} fill="none" stroke={colors[0]} strokeWidth="3" strokeLinecap="round" strokeLinejoin="round" />}{values.map((value, index) => <Circle key={index} cx={xAt(index)} cy={yAt(value)} r={scatter ? 6 : 4} fill={colors[index]} />)}</>; }
function Bars({ values, colors, xAt, yAt, baseline, candlestick }: { values: number[]; colors: string[]; xAt: (index: number) => number; yAt: (value: number) => number; baseline: number; candlestick: boolean }) { return <>{values.map((value, index) => candlestick ? <G key={index}><Line x1={xAt(index)} x2={xAt(index)} y1={yAt(value)} y2={baseline} stroke={colors[index]} strokeWidth="2" /><Rect x={xAt(index) - 11} y={yAt(value)} width={22} height={Math.max(5, baseline - yAt(value))} fill={index % 2 ? "transparent" : colors[index]} stroke={colors[index]} strokeWidth="2" /></G> : <Rect key={index} x={xAt(index) - 16} y={yAt(value)} width={32} height={baseline - yAt(value)} rx={5} fill={colors[index]} />)}</>; }
function Pie({ values, colors }: { values: number[]; colors: string[] }) { const total = values.reduce((sum, value) => sum + value, 0); if (!total) return <SvgText x="160" y="90" textAnchor="middle" fontSize="12" fill="#64748B">لا توجد بيانات</SvgText>; const radius = 46; const circumference = 2 * Math.PI * radius; let offset = 0; return <>{values.map((value, index) => { const dash = circumference * value / total; const element = <Circle key={index} cx="160" cy="84" r={radius} stroke={colors[index]} strokeWidth="24" strokeDasharray={`${dash} ${circumference - dash}`} strokeDashoffset={-offset} fill="none" transform="rotate(-90 160 84)" />; offset += dash; return element; })}</>; }
function Radar({ values, colors }: { values: number[]; colors: string[] }) { const centerX = 160; const centerY = 82; const radius = 58; const point = (index: number, value: number) => { const angle = index * Math.PI * 2 / 3 - Math.PI / 2; return `${centerX + Math.cos(angle) * radius * value / 100},${centerY + Math.sin(angle) * radius * value / 100}`; }; return <><Polygon points={values.map((_, index) => point(index, 100)).join(" ")} fill="none" stroke="#CBD5E1" /><Polygon points={values.map((value, index) => point(index, value)).join(" ")} fill={colors[0] + "30"} stroke={colors[0]} strokeWidth="2" /></>; }

const styles = StyleSheet.create({ card: { borderWidth: 1, borderRadius: 18, padding: 14 }, title: { fontSize: 15, fontWeight: "800", textAlign: "right", marginBottom: 6 } });
