import { useState } from "react";
import { StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { MaterialIcons } from "@expo/vector-icons";

import { useColors } from "@/hooks/use-colors";
import { useHasPermission } from "@/lib/app-context";
import type { PermissionModule } from "@/lib/user-permissions-model";

export function ReportFab({ module, addLabel, onAdd, onImport, onSettings, extraActions = [], onExport, exporting }: { module?: PermissionModule; addLabel?: string; onAdd?: () => void; onImport?: () => void; onSettings?: () => void; extraActions?: Array<{ icon: keyof typeof MaterialIcons.glyphMap; label: string; color?: string; onPress: () => void }>; onExport: (format: "pdf" | "excel") => void; exporting?: "pdf" | "excel" | null }) {
  const colors = useColors(); const [open, setOpen] = useState(false); const closeThen = (action: () => void) => { setOpen(false); action(); };
  const canCreate = useHasPermission(module || "dashboard", "create"); const canManage = useHasPermission(module || "dashboard", "manage"); const canExport = useHasPermission(module || "dashboard", "export");
  const visibleAdd = canCreate ? onAdd : undefined; const visibleImport = canCreate ? onImport : undefined; const visibleSettings = canManage ? onSettings : undefined; const visibleExtras = canManage ? extraActions : [];
  return <View style={styles.wrap}>{open ? <View style={[styles.menu, { backgroundColor: colors.surface, borderColor: colors.border }]}>{visibleAdd || visibleImport || visibleExtras.length ? <><Text style={[styles.header, { color: colors.muted }]}>إدارة</Text>{visibleAdd ? <Item icon="add" label={addLabel || "إضافة"} colors={colors} onPress={() => closeThen(visibleAdd)} /> : null}{visibleImport ? <Item icon="file-download" label="استيراد استبيان" colors={colors} onPress={() => closeThen(visibleImport)} /> : null}{visibleExtras.map((action) => <Item key={action.label} icon={action.icon} label={action.label} color={action.color} colors={colors} onPress={() => closeThen(action.onPress)} />)}<View style={[styles.divider, { backgroundColor: colors.border }]} /></> : null}{visibleSettings ? <><Text style={[styles.header, { color: colors.muted }]}>إعداد التقرير</Text><Item icon="tune" label="إعدادات التقرير" colors={colors} onPress={() => closeThen(visibleSettings)} /><View style={[styles.divider, { backgroundColor: colors.border }]} /></> : null}{canExport ? <><Text style={[styles.header, { color: colors.muted }]}>تصدير التقرير</Text><Item icon="picture-as-pdf" label={exporting === "pdf" ? "جارٍ إنشاء PDF..." : "تقرير PDF"} color={colors.error} disabled={Boolean(exporting)} colors={colors} onPress={() => closeThen(() => onExport("pdf"))} /><Item icon="table-chart" label={exporting === "excel" ? "جارٍ إنشاء Excel..." : "ملف Excel"} color={colors.success} disabled={Boolean(exporting)} colors={colors} onPress={() => closeThen(() => onExport("excel"))} /></> : null}</View> : null}<TouchableOpacity onPress={() => setOpen((value) => !value)} style={[styles.fab, { backgroundColor: colors.primary }]} accessibilityLabel="إدارة وتصدير"><MaterialIcons name={open ? "close" : "more-horiz"} size={27} color="#fff" /></TouchableOpacity></View>;
}

function Item({ icon, label, color, colors, disabled, onPress }: { icon: keyof typeof MaterialIcons.glyphMap; label: string; color?: string; colors: ReturnType<typeof useColors>; disabled?: boolean; onPress: () => void }) { return <TouchableOpacity disabled={disabled} onPress={onPress} style={[styles.item, disabled && styles.disabled]}><MaterialIcons name={icon} size={19} color={color || colors.primary} /><Text style={[styles.itemText, { color: colors.foreground }]}>{label}</Text></TouchableOpacity>; }

const styles = StyleSheet.create({ wrap: { position: "absolute", right: 18, bottom: 20, alignItems: "flex-start", gap: 10, zIndex: 30 }, fab: { width: 58, height: 58, borderRadius: 29, alignItems: "center", justifyContent: "center", elevation: 5 }, menu: { minWidth: 188, borderWidth: 1, borderRadius: 16, paddingVertical: 7, elevation: 4 }, header: { fontSize: 10, fontWeight: "800", paddingHorizontal: 13, paddingTop: 5, textAlign: "left" }, item: { minHeight: 43, paddingHorizontal: 13, flexDirection: "row", alignItems: "center", gap: 8 }, itemText: { fontSize: 12, fontWeight: "800" }, divider: { height: 1, marginVertical: 5 }, disabled: { opacity: 0.55 } });
