import * as FileSystem from "expo-file-system/legacy";
import * as Print from "expo-print";
import * as Sharing from "expo-sharing";
import * as XLSX from "xlsx";
import { Alert, Platform } from "react-native";

import { ensureDirectoryExists, sanitizeFilename } from "./export-sanitizer";
import { recordGeneratedReport } from "./report-history";
import { loadSharedPdfReportLogo, pdfLogoMarkup } from "./pdf-report-logo";

export interface TabReportData { title: string; filename: string; columns: string[]; rows: Record<string, unknown>[]; }

function escapeHtml(value: unknown): string { return String(value ?? "—").replace(/[&<>'"]/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" })[character] || character); }
function cell(value: unknown): string { if (value === undefined || value === null || value === "") return "—"; return Array.isArray(value) ? value.join("، ") : String(value); }
function reportHtml(report: TabReportData, logoMarkup = ""): string { const rows = report.rows.map((row) => `<tr>${report.columns.map((column) => `<td>${escapeHtml(cell(row[column]))}</td>`).join("")}</tr>`).join("") || `<tr><td colspan="${report.columns.length}">لا توجد بيانات ضمن النطاق المحدد.</td></tr>`; return `<!DOCTYPE html><html lang="ar" dir="rtl"><head><meta charset="utf-8"/><style>@page{size:A4 landscape;margin:12mm}*{box-sizing:border-box}body{direction:rtl;font-family:Tahoma,Arial,sans-serif;color:#172033;font-size:10px}.report-head{display:flex;gap:12px;align-items:center;margin-bottom:17px}.shared-report-logo{width:48px;height:48px;object-fit:contain;border-radius:10px}h1{font-size:23px;color:#1455b8;margin:0 0 6px}.meta{color:#64748b}table{width:100%;border-collapse:collapse}th{background:#1f5eb8;color:#fff;font-weight:bold}th,td{padding:8px;border-bottom:1px solid #e1e8f2;text-align:right;vertical-align:top}tr:nth-child(even){background:#f8fbff}@media print{tr{break-inside:avoid}}</style></head><body><header class="report-head">${logoMarkup}<div><h1>${escapeHtml(report.title)}</h1><div class="meta">تاريخ الإنشاء: ${new Date().toLocaleString("en-US")}</div></div></header><table><thead><tr>${report.columns.map((column) => `<th>${escapeHtml(column)}</th>`).join("")}</tr></thead><tbody>${rows}</tbody></table></body></html>`; }
function workbookBase64(report: TabReportData): string { const sheet = XLSX.utils.json_to_sheet(report.rows.map((row) => Object.fromEntries(report.columns.map((column) => [column, cell(row[column])]))), { header: report.columns }); (sheet as XLSX.WorkSheet & { "!dir"?: string })["!dir"] = "rtl"; sheet["!cols"] = report.columns.map((column) => ({ wch: Math.max(15, Math.min(32, column.length + 10)) })); sheet["!autofilter"] = { ref: XLSX.utils.encode_range({ s: { c: 0, r: 0 }, e: { c: report.columns.length - 1, r: Math.max(report.rows.length, 1) } }) }; const workbook = XLSX.utils.book_new(); workbook.Workbook = { Views: [{ RTL: true }] }; XLSX.utils.book_append_sheet(workbook, sheet, report.title.slice(0, 28) || "تقرير"); return XLSX.write(workbook, { bookType: "xlsx", type: "base64", compression: true }) as string; }
async function destination(filename: string, extension: "pdf" | "xlsx") { if (!FileSystem.documentDirectory) throw new Error("لم يتمكن التطبيق من الوصول إلى مجلد المستندات"); const directory = `${FileSystem.documentDirectory}reports/`; if (!(await ensureDirectoryExists(directory))) throw new Error("تعذر إنشاء مجلد التقارير"); const safeFilename = sanitizeFilename(filename, extension); return { uri: `${directory}${safeFilename}`, safeFilename }; }
async function shareAndRecord(uri: string, safeFilename: string, type: "PDF" | "XLSX", title: string) { const info = await FileSystem.getInfoAsync(uri); if (!info.exists || info.isDirectory || !info.size) throw new Error("لم يتم اعتماد ملف فارغ أو غير مكتمل"); await recordGeneratedReport({ title: safeFilename, type, uri, size: info.size }); if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(uri, { mimeType: type === "PDF" ? "application/pdf" : "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", UTI: type === "PDF" ? "com.adobe.pdf" : "org.openxmlformats.spreadsheetml.sheet", dialogTitle: `مشاركة ${title}` }); else Alert.alert("تم الحفظ", `حُفظ التقرير داخل مجلد التقارير بالتطبيق:\n${safeFilename}`); }

export async function exportTabReportPdf(report: TabReportData): Promise<void> { if (!report.rows.length) { Alert.alert("تنبيه", "لا توجد بيانات لتصديرها."); return; } if (Platform.OS === "web") { Alert.alert("التصدير من الويب", "تصدير PDF متاح في تطبيق الهاتف."); return; } try { const logoMarkup = pdfLogoMarkup(await loadSharedPdfReportLogo()); const generated = await Print.printToFileAsync({ html: reportHtml(report, logoMarkup) }); const { uri, safeFilename } = await destination(`${report.filename}_${Date.now()}`, "pdf"); await FileSystem.copyAsync({ from: generated.uri, to: uri }); await shareAndRecord(uri, safeFilename, "PDF", report.title); } catch (error) { Alert.alert("فشل تصدير PDF", error instanceof Error ? error.message : "خطأ غير معروف"); } }
export async function exportTabReportExcel(report: TabReportData): Promise<void> { if (!report.rows.length) { Alert.alert("تنبيه", "لا توجد بيانات لتصديرها."); return; } if (Platform.OS === "web") { Alert.alert("التصدير من الويب", "تصدير Excel متاح في تطبيق الهاتف."); return; } try { const { uri, safeFilename } = await destination(`${report.filename}_${Date.now()}`, "xlsx"); await FileSystem.writeAsStringAsync(uri, workbookBase64(report), { encoding: FileSystem.EncodingType.Base64 }); await shareAndRecord(uri, safeFilename, "XLSX", report.title); } catch (error) { Alert.alert("فشل تصدير Excel", error instanceof Error ? error.message : "خطأ غير معروف"); } }
